version: "3"
services:
# ------------Support services-------------
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      
#  matchdb:
#    image: mongo
#    ports:
#      - "27017:27017"

  mongodb:
    image: mongo

  mysqldb:
    image: jaspermaes/arenamanagement:mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
  
  # -------------Main services---------------
    
  membermanagement:
    build: ./sportarena-app-member-management
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    #ports:
      #- "2227:2227"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  gamblingmanagement:
    build: ./sportarena-app-gambling-management
    links:
      - mongodb
      - kafka
      - zookeeper
    depends_on:
      - mongodb
      - kafka
      - zookeeper
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_PROFILES_ACTIVE=docker

  cateringmanagement:
    build: ./sportarena-app-catering-management
    links:
      - kafka
      - zookeeper
      - mysqldb
    depends_on:      
      - kafka
      - zookeeper
      - mysqldb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  authorization:
    build: ./sportarena-app-authorization-service
    depends_on:
      - membermanagement
    #ports:
      #- "2228:2228"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      
  apigateway:
    build: ./sportarena-app-api-gateway
    links:
      - membermanagement
      - authorization
      - gamblingmanagement
    depends_on:
      - membermanagement
      - authorization
      - gamblingmanagement
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  staffmanagement:
    build: ./sportarena-app-arena-staff-management
    links:
      - kafka
      - zookeeper
      - mysqldb
    depends_on:
      - kafka
      - zookeeper
      - mysqldb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ticketmanagement:
    build: ./sportarena-app-ticket-management
    links:
      - kafka
      - zookeeper
      - mongodb
    depends_on:
      - kafka
      - zookeeper
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_PROFILES_ACTIVE=docker


  arenamanagement:
    build: ./sportarena-app-arena-management
    links:
      - kafka
      - zookeeper
      - mongodb
    depends_on:
      - kafka
      - zookeeper
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_PROFILES_ACTIVE=docker
