
server:
  port: 2228
okta:
  oauth2:
    issuer: https://dev-883704.okta.com/oauth2/default
    clientId: 0oa2dcmzszo291nTr357
    clientSecret: I0-aCD4lEDLTWsLwgm8_oIdRqomv7UwezZ2ibXET
    groupsClaim: groups
    redirect-uri: /okta/login/oauth2
    
spring.thymeleaf.cache: false

frontend.url: http://localhost:9000/authorization/register


#spring.kafka.bootstrap-servers: bootstrap.kafka:9092
spring.cloud.stream.kafka.binder.zkNodes: zookeeper
spring.cloud.stream.kafka.binder.brokers: kafka

spring.cloud.stream.bindings.register_member: register_member
spring.cloud.stream.bindings.register_member.content-type: application/json

spring.cloud.stream.bindings.register_member_timeout: register_member_timeout
spring.cloud.stream.bindings.register_member_timeout.content-type: application/json

spring.cloud.stream.bindings.register_catering: register_catering
spring.cloud.stream.bindings.register_catering.content-type: application/json

spring.cloud.stream.bindings.register_catering_timeout: register_catering_timeout
spring.cloud.stream.bindings.register_catering_timeout.content-type: application/json

spring.cloud.stream.bindings.register_staff_timeout: register_staff_timeout
spring.cloud.stream.bindings.register_staff_timeout.content-type: application/json

spring.cloud.stream.bindings.register_staff: register_staff
spring.cloud.stream.bindings.register_staff.content-type: application/json

spring.cloud.stream.bindings.register_result: register_result
spring.cloud.stream.bindings.register_result.content-type: application/json