package be.ugent.groep10.catering.domain;

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class ScheduleItem {
	//In tegenstelling tot de scheduleitem klasse in Arena Mgmt 
	//mag deze NIET autogenerated worden, anders wijken de ID's af van elkaar
	//naargelang de volgorde waarin de messages ontvangen worden
	@Id 
	private String sportEventId;
	
	private LocalDateTime dateTimeBegin;
	private LocalDateTime dateTimeEnd;
	private String description;
	private int seatOccupation;
	
	//Constructors
	public ScheduleItem() {
		
	}
	
	public ScheduleItem(String sportEventId, LocalDateTime startTime, LocalDateTime endTime, String description, int seatOccupation) {
		this.sportEventId = sportEventId;
		this.setDateTimeBegin(endTime);
		this.setDateTimeEnd(endTime);
		this.setDescription(description);
		this.setSeatOccupation(seatOccupation);
	}
	
	//Getters-Setters
	public String getSportEventId() {
		return this.sportEventId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getSeatOccupation() {
		return seatOccupation;
	}

	public void setSeatOccupation(int seatOccupation) {
		this.seatOccupation = seatOccupation;
	}

	public LocalDateTime getDateTimeBegin() {
		return dateTimeBegin;
	}

	public void setDateTimeBegin(LocalDateTime dateTimeBegin) {
		this.dateTimeBegin = dateTimeBegin;
	}

	public LocalDateTime getDateTimeEnd() {
		return dateTimeEnd;
	}

	public void setDateTimeEnd(LocalDateTime dateTimeEnd) {
		this.dateTimeEnd = dateTimeEnd;
	}
	
}
