package be.ugent.groep10.catering.domain;

import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class ScheduleItem {
	//In tegenstelling tot de scheduleitem klasse in Arena Mgmt 
	//mag deze NIET autogenerated worden, anders wijken de ID's af van elkaar
	//naargelang de volgorde waarin de messages ontvangen worden
	@Id 
	private String sportEventId;
	
	private String startTime;
	private String endTime;
	private String description;
	private int seatOccupation;
	
	//Constructors
	public ScheduleItem() {
		
	}
	
	public ScheduleItem(String sportEventId, String startTime, String endTime, String description, int seatOccupation) {
		this.sportEventId = sportEventId;
		this.setStartTime(startTime);
		this.setEndTime(endTime);
		this.setDescription(description);
		this.setSeatOccupation(seatOccupation);
	}
	
	//Getters-Setters
	public String getSportEventId() {
		return this.sportEventId;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getSeatOccupation() {
		return seatOccupation;
	}

	public void setSeatOccupation(int seatOccupation) {
		this.seatOccupation = seatOccupation;
	}
	
}
